# Docker version installed on target host
docker_version: "17.12.0~ce-0~debian"

# Docker image name for running Bitcoin Core
# See: https://github.com/vtorhonen/lightning-node
docker_image_bitcoind: "vtorhonen/bitcoind:0.15.1-1"

# Docker image for running Lightning Network
# Note: runs latest & greatest from master branch on
# c-lightning git repository for now.
# See: https://github.com/ElementsProject/lightning
docker_image_lightningd: "vtorhonen/lightningd:latest"

# Data directory used by both containers as follows:
# - bitcoind: '/data/bitcoind'
# - c-lightning: '/data/c-lightning'
# Directory will be created if it doesn't exist.
# Make sure you have mounted '/data' before running this playbook.
data_dir: "/data"

# Lightning color + alias settings
lightningd_rgb: "666666"
lightningd_alias: "big-blockers-rip"