# Docker version installed on target host
docker_version: "18.06.1~ce~3-0~debian"

# Docker image name for running Bitcoin Core
# See: https://github.com/vtorhonen/lightning-node/tree/master/bitcoind
docker_image_bitcoind: "vtorhonen/bitcoind:0.16.3-1"

# Docker image for running Lightning Network
# See: https://github.com/vtorhonen/lightning-node/tree/master/lightningd
docker_image_lightningd: "vtorhonen/lightningd:0.6.1-2"

# Data directory used by both containers as follows:
# - bitcoind: '/data/bitcoind'
# - c-lightning: '/data/c-lightning'
# Directory will be created if it doesn't exist.
# Make sure you have mounted '/data' before running this playbook.
data_dir: "/data"

# Lightning color + alias settings
lightningd_rgb: "666666"
lightningd_alias: "big-blockers-rip"
